### ISSUE TITLE
can you share the paper, I can not find it in the internet

### ISSUE THREAD

**Issue by ltcxjtu** [Xiaobin-Rong/gtcrn#1]
hello,man?

**Comment by Xiaobin-Rong** [comment]
Yes, the paper has not been publicly available online. In fact, this is the paper I submitted to ICASSP 2024 this year, and it is currently under review. If the review process is successful, I will update it here promptly. Thanks for your ongoing interest and support!

**Comment by ltcxjtu** [comment]
I'm looking forward,the parameter quantity of the Model is really attractive.

**Comment by Xiaobin-Rong** [comment]
@ltcxjtu 
感谢你的关注，paper已经见刊: https://ieeexplore.ieee.org/document/10448310

**Comment by limmark21** [comment]
could you please share pdf file, i cannot download paper from link(

**Comment by Xiaobin-Rong** [comment]
@limmark21 
[GTCRN_A_Speech_Enhancement_Model_Requiring_Ultralow_Computational_Resources.pdf](https://github.com/Xiaobin-Rong/gtcrn/files/15234641/GTCRN_A_Speech_Enhancement_Model_Requiring_Ultralow_Computational_Resources.pdf)

**Comment by limmark21** [comment]
THANK YOU SO MUCH, I just have started to explore speech enhancement models. But your gtcrn made a big impression on me!

**Comment by Xiaobin-Rong** [comment]
@limmark21 
You're welcome, and thank you for your kind words! I wish you smooth progress in your research.
