### ISSUE TITLE
计算量是否可以进一步下探

### ISSUE THREAD

**Issue by kaidachen** [Xiaobin-Rong/gtcrn#22]
作者您好，
     感谢您开源出优秀的模型！
     请问计算量是否可以进一步下探，您论文中的模型约39.6M MACs，请问如果将计算量压缩到10M以内有什么方案。比如减少卷积通道数最小可以到多少。

期待您的回复，祝您科研顺利。

**Comment by Xiaobin-Rong** [comment]
您好！
如 README 中所说明的，模型的实际运算量是 33 MMACs，将计算量压到 10M 以内我认为非常困难，”通道数最小可以到多少“ 应该需要实验探索。但是单纯靠减少通道数来压计算量将会导致性能严重劣化。
