### ISSUE TITLE
关于流式推理GRU状态值传递的疑问

### ISSUE THREAD

**Issue by IwraI** [Xiaobin-Rong/gtcrn#25]
你好，关于流式推理时，DPGRNN模块中的intra_rnn和inter_rnn，为什么只传递了inter rnn的状态值，intra rnn的不需要传递吗？传递了的话会有什么影响。
![image](https://github.com/user-attachments/assets/ea6318c4-f206-41d5-a0d9-fdf9d642685d)

**Comment by Xiaobin-Rong** [comment]
因为 intra_rnn 是双向的 LSTM，在 F 维度进行 hidden state 的传递，这部分已经内置在 nn.LSTM 里面了。intra_rnn 与时间维度无关，不影响因果性，故在流式转换时不需要改写
