### ISSUE TITLE
请问您排查到onnxsim.simplify导出时的问题所在了吗

### ISSUE THREAD

**Issue by SherryYu33** [Xiaobin-Rong/gtcrn#3]
首先非常感谢您的工作，我这里使用onnxsim.simplify导出时会报这个错
`RuntimeError: /project/third_party/onnx-optimizer/onnxoptimizer/passes/eliminate_shape_gather.h:48: runTransform: Assertion 'indices_val < dims.size()' failed.`
我和DeepVQE对比后排查了如下的地方：
chunk改切片
转置卷积去掉
groups去掉
空洞卷积去掉
layernorm去掉
均没有排查到原因，还是报上述的错
请问您找到问题在哪了吗

**Comment by SherryYu33** [comment]
我发现把perform_optimization关了可以运行，但是实时率没有明显的变化
model_simp, check = simplify(onnx_model, perform_optimization=False)

**Comment by SherryYu33** [comment]
目前已成功完成simplify，改动如下：
chunk改切片，reshape和rearrange改view，并且在需要的地方contiguous，虽然不知道为什么但是就是可以了。。

**Comment by Xiaobin-Rong** [comment]
@SherryYu33 
由于最近忙别的事情，后续就没有继续排查错误了。非常感谢你的工作！可能是由于onnxsim对一些算子不支持。后续我会根据你所说的来修正代码，再次感谢！
