### ISSUE TITLE
模型在rk3566上的速度依旧有点慢

### ISSUE THREAD

**Issue by yuyun2000** [Xiaobin-Rong/gtcrn#33]
我承认这个模型的速度已经非常快，但是在rk3566 四核心a55上，依然满足不了实时的要求
流式的模型单次推理16ms，端侧推理一次耗时14-16ms，再加上其他应用很容易就rtf>1了
有可能进一步减少模型的size吗？

**Comment by yuyun2000** [comment]
或者说 可以将采样率将低为8k吗？ 这样实时率理论上就翻倍了

**Comment by Xiaobin-Rong** [comment]
可以尝试将采样率降为8k，但模型的结构参数要相应地调整。性能应该也会有下降。

**Comment by renshujiajia** [comment]
提问，为什么不用npu进行计算呢

**Comment by yuyun2000** [comment]
> 提问，为什么不用npu进行计算呢

目前npu工具链并不是很完善，这种复杂的模型他不太能部署

**Comment by yuyun2000** [comment]
> 可以尝试将采样率降为8k，但模型的结构参数要相应地调整。性能应该也会有下降。

请问这样修改后需要重新训练吗？还得自己训练吧？

**Comment by Xiaobin-Rong** [comment]
> > 可以尝试将采样率降为8k，但模型的结构参数要相应地调整。性能应该也会有下降。
> 
> 请问这样修改后需要重新训练吗？还得自己训练吧？

是的，模型结构已经改变了，数据也变了，当然要重新训练

**Comment by yuyun2000** [comment]
> > > 可以尝试将采样率降为8k，但模型的结构参数要相应地调整。性能应该也会有下降。
> > 
> > 
> > 请问这样修改后需要重新训练吗？还得自己训练吧？
> 
> 是的，模型结构已经改变了，数据也变了，当然要重新训练

感谢老师的指导
