### ISSUE TITLE
The training target is obtained by preserving the first 100 ms reflections

### ISSUE THREAD

**Issue by zdongchen** [Xiaobin-Rong/gtcrn#40]
请问论文3.1 Datasets 在数据集制作时 "训练目标是通过保留前 100 毫秒反射来实现的" 这句话是什么意思，不太能理解，望解答，感谢

**Comment by Xiaobin-Rong** [comment]
通过保留早期混响，让clean可以和含混响的noisy的在时域上对齐。这也是大部分SE文章的做法
