### ISSUE TITLE
请教一下Temporal Recurrent Attention的作用

### ISSUE THREAD

**Issue by JaySpeech** [Xiaobin-Rong/gtcrn#5]
Hello 新年好， 请问下 Temporal Recurrent Attention的具体作用应该如何理解？

**Comment by Xiaobin-Rong** [comment]
同祝新年好！
Temporal Recurrent Attention 是基于 **Time Attention** (Q. Zhang, X. Qian, Z. Ni, A. Nicolson, E. Ambikairajah and H. Li, "A Time-Frequency Attention Module for Neural Speech Enhancement," in IEEE/ACM Transactions on Audio, Speech, and Language Processing, vol. 31, pp. 462-475, 2023) 的改进。
文章预计三月中旬将会见刊，欢迎你持续的关注！

**Comment by JaySpeech** [comment]
感谢帮助。
